import type {Metadata} from "next";
import "@/style/globals.css";


export const metadata: Metadata = {
    title: "Tiketen - Temukan tiket kesukaan kamu!",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            {children}
        </div>
    );
}
