import type {Metadata} from "next";
import "@/style/globals.css";
import {UserSidebar} from "@/components/User/Sidebar";
import { auth } from "@/auth";
import { getCurrentOrganization } from "@/action/get-user-details";
import { OrganizationDetails } from "@/types/type";


export const metadata: Metadata = {
    title: "Tiketen - Profil",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth()
    const currentOrganizer = await getCurrentOrganization(
        session?.user?.id as string
    );

    return (
        <div className="max-w-[1400] mx-auto flex gap-5">
            <UserSidebar Organization={currentOrganizer as OrganizationDetails}  />
            {children}
        </div>
    );
}
