import type {Metadata} from "next";
import "@/style/globals.css";
import {UserSidebar} from "@/components/User/Sidebar";


export const metadata: Metadata = {
    title: "Tiketen - Profil",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="max-w-[1400] mx-auto flex gap-5">
            <UserSidebar />
            {children}
        </div>
    );
}
