import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@/style/globals.css";
import TopNav from "@/components/ui/top-nav";
import {Toaster} from "@/components/ui/sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Tiketen - Temukan tiket mu disini",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <TopNav />
        <main className="p-10 w-full">
            {children}
            <Toaster />
        </main>
        </body>
        </html>
    );
}
