import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "@/style/globals.css";
import TopNav from "@/components/ui/top-nav";
import {Toaster} from "@/components/ui/sonner";
import { auth } from "@/auth";
import {SyncDeviceInfo} from "@/components/SyncDeviceInfo";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Tiketen - Temukan tiket mu disini",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth()
    const accessToken = session?.user.access_token
    const userId = session?.user.id


    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <TopNav />
        <main className="p-10 w-full">
            {children}
            <Toaster position={"top-right"} richColors={true} closeButton />

            {accessToken && <SyncDeviceInfo access_token={accessToken} user_id={userId as string} />}
        </main>
        </body>
        </html>
    );
}
