import type {Metadata} from "next";
import "@/style/globals.css";
import {UserSidebar} from "@/components/User/Sidebar";
import { auth } from "@/auth";
import { getCurrentOrganization } from "@/action/get-user-details";
import { OrganizationDetails } from "@/types/type";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
    title: "Tiketen - Profil",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await auth()

    return (
		<div className="max-w-7xl mx-auto flex gap-5">
			<UserSidebar />
			<SessionProvider>{children}</SessionProvider>
		</div>
	);
}
